### ISSUE TITLE
Have to register new primitives/pipelines before debugging

### ISSUE THREAD

**Issue by ZhuofanXie** [data-dev/DataTracer#18]
* DataTracer version: 0.0.6.dev0
* Python version: 3.7.4
* Operating System: MacOS 10.15.6

### Description

Currently, for developers implementing new pipelines/primitives, they have to re-install the package to register their pipelines/primitives before they can start debugging their pipelines/primitives, which is inconvenient.

### Proposed Solution

We can make use of the existing default pipeline/primitive directories: `datatracer/jsons/{pipelines, primitives}`. When the pipeline/primitive name is not found by `mlblocks`, we can search the `json` files in these directories and load them instead. This way, the `datatracer` can be run directly from local files without installation first.

**Comment by csala** [comment]
> Currently, for developers implementing new pipelines/primitives, they have to re-install the package to register their pipelines/primitives before they can start debugging their pipelines/primitives, which is inconvenient.

Hi @ZhuofanXie I think this is not really necessary. When you install DataTracer the `jsons/primitives` and `jsons/pipelines` folder is already registered as an entry point for MLBlocks, so any pipeline or primitive that you add to these folders should be already available for usage.

You can read more about how this is set up here: https://mlbazaar.github.io/MLBlocks/advanced_usage/adding_primitives.html#developing-a-primitives-library
